### ISSUE TITLE
Can't Run Hotkeys Asynchronously

### ISSUE THREAD

**Issue by clu7ch3r** [thomaslevesque/NHotkey#31] opened 2021-01-15 03:58 UTC
I have two hotkeys set, one to perform an action and the other to cancel it. The problem is that when I call the second hotkey while the first hotkey is doing something, it doesn't trigger until after the first one is done.

```
HotkeyManager.Current.AddOrReplace("Paste", HkTextBox.Hotkey.Key, HkTextBox.Hotkey.Modifiers, AutoPaste);
HotkeyManager.Current.AddOrReplace("CancelPaste", Key.Escape, ModifierKeys.Alt, CancelPaste);
```

**Comment by thomaslevesque** [comment] 2021-01-15 09:34
Hi @clu7ch3r,

I suspect the problem is that your Paste action is executing on the UI thread (a.k.a. "main thread"), preventing the app from processing new messages on that thread. I don't think it's related to NHotkey at all; you would have the same problem if you used buttons to trigger and cancel the action.

For that to work, you would need to perform the Paste action on a separate thread (at least the part that needs to be cancelable)

**Comment by clu7ch3r** [comment] 2021-01-16 00:27
I tried wrapping the functionalities of the CancelPaste method in a new thread which ends up running synchronously.

```
HotkeyManager.Current.AddOrReplace("Paste", HkTextBox.Hotkey.Key, HkTextBox.Hotkey.Modifiers, AutoPaste);
HotkeyManager.Current.AddOrReplace("CancelPaste", Key.Escape, ModifierKeys.Alt, CancelPaste);

private void CancelPaste(object sender, HotkeyEventArgs e)
{
    Thread thread = new Thread(new ThreadStart(() =>
    {
        MessageBox.Show("Test");
        //Paste = false;
        e.Handled = true;
    }));
    thread.Start();
}
```

I also tried placing the whole hotkey in a separate thread which gives me this exception at runtime: `COMException: 'Invalid window; it belongs to other thread.`

```
HotkeyManager.Current.AddOrReplace("Paste", HkTextBox.Hotkey.Key, HkTextBox.Hotkey.Modifiers, AutoPaste);
Thread thread = new Thread(new ThreadStart(() => HotkeyManager.Current.AddOrReplace("CancelPaste", Key.Escape, ModifierKeys.Alt, CancelPaste)));
thread.Start();

private void CancelPaste(object sender, HotkeyEventArgs e)
{
    MessageBox.Show("Test");
    //Paste = false;
    e.Handled = true;
}
```

**Comment by thomaslevesque** [comment] 2021-01-17 14:05
It's AutoPaste that needs to run in a separate thread, not CancelPaste
Registering the hotkey in a separate thread isn't necessary. The implementation of AutoPaste should spin up a new thread.

**Comment by clu7ch3r** [comment] 2021-01-19 10:52
I get InvalidOperationException on `Thread.Sleep` when I wrap it on AutoPaste.

![image](https://user-images.githubusercontent.com/36937310/105024540-3896f980-5a1a-11eb-9629-2e95a0902b73.png)

**Comment by thomaslevesque** [comment] 2021-01-19 13:28
Ah, I see. If AutoPaste is doing things that have to be done on the UI thread, then you can't do it on a separate thread.

What does `input.Keyboard.Sleep` do? Is it any different from `Thread.Sleep`? If it's actually the same thing, you could make your method asynchronous and use `Task.Delay`:

```csharp
await Task.Delay((int)Delay.Value);
input.Keyboard.KeyPress(...)
```
This should free the UI thread during the sleep, so that it can handle other hotkeys.

Another alternative would be to call [the WPF equivalent of `Application.DoEvents`](https://stackoverflow.com/questions/4502037/where-is-the-application-doevents-in-wpf) in your loop, but it won't work during the call to `Sleep`.

**Comment by clu7ch3r** [comment] 2021-01-21 14:59
I tried running a new thread on both individually and together but it's still running synchronously. The only difference this time is that the message box pops up on the screen without me having to click on the application.

```
private void AutoPaste(object sender, HotkeyEventArgs e)
{
    Task.Factory.StartNew(() =>
    {
        Dispatcher.BeginInvoke(DispatcherPriority.Background, new Action(() =>
        {
            if (WindowState != WindowState.Minimized)
            {
                WindowState = WindowState.Minimized;
                Thread.Sleep(TimeSpan.FromSeconds(1));
            }

            Paste = true;
            InputSimulator input = new InputSimulator();

            for (int i = 0; i < clipboardHistoryItems.Count && Paste; i++)
            {
                Clipboard.SetHistoryItemAsContent(clipboardHistoryItems[i]);
                input.Keyboard.Sleep((int)Delay.Value).ModifiedKeyStroke(VirtualKeyCode.CONTROL, VirtualKeyCode.VK_V);
                switch (DelimiterComboBox.SelectedIndex)
                {
                    case 1:
                        input.Keyboard.Sleep((int)Delay.Value).KeyPress(VirtualKeyCode.TAB);
                        break;
                    ...
                }
            }
        }));
    });

private void CancelPaste(object sender, HotkeyEventArgs e)
{
    Task.Factory.StartNew(() =>
    {
        Dispatcher.BeginInvoke(DispatcherPriority.Background, new Action(() =>
        {
            MessageBox.Show("Test");
            //Paste = false;
        }));                
    });
    e.Handled = true;
}
```

**Comment by thomaslevesque** [comment] 2021-01-21 16:58
`Task.Factory.StartNew` means "run that on a new thread.
But `Dispatcher.BeginInvoke` means "run that on the UI thread".
So there's no point in starting a new thread just to execute something on the UI thread...

I gave you a few suggestions on how to fix the problem in my previous message, have you tried them? I checked what `input.Keyboard.Sleep` does, it's just a `Thread.Sleep`. So I suggest you do it like this:

```csharp
private CancellationTokenSource _autoPasteCancellation;

private async void AutoPaste(object sender, HotkeyEventArgs e)
{
    try
    {
        _autoPasteCancellation = new CancellationTokenSource();
        var cancellationToken = _autoPasteCancellation.Token;
        if (WindowState != WindowState.Minimized)
        {
            WindowState = WindowState.Minimized;
            await Task.Delay(TimeSpan.FromSeconds(1), cancellationToken);
        }

        InputSimulator input = new InputSimulator();

        for (int i = 0; i < clipboardHistoryItems.Count; i++)
        {
            Clipboard.SetHistoryItemAsContent(clipboardHistoryItems[i]);
            await Task.Delay((int)Delay.Value, cancellationToken);
            input.Keyboard.ModifiedKeyStroke(VirtualKeyCode.CONTROL, VirtualKeyCode.VK_V);
            switch (DelimiterComboBox.SelectedIndex)
            {
                case 1:
                    await Task.Delay((int)Delay.Value, cancellationToken);
                    input.Keyboard.KeyPress(VirtualKeyCode.TAB);
                    break;
                ...
            }
        }

        e.Handled = true;

    }
    catch (OperationCanceledException)
    {
        // The operation was aborted
    }
    catch(Exception ex)
    {
        // Always catch exceptions in an async void method, otherwise it can crash the process
        MessageBox.Show(ex.Message);
    }
    finally
    {
        if (_autoPasteCancellation != null)
            _autoPasteCancellation.Dispose();
        _autoPasteCancellation = null;
    }
}

private void CancelPaste(object sender, HotkeyEventArgs e)
{
    if (_autoPasteCancellation != null)
    {
        _autoPasteCancellation.Cancel();
    }
    e.Handled = true;
}
```

Anyway, the problems you're having have nothing to do with NHotkey, so I'm going to close this issue.

**Closed** 2021-01-21 16:58 UTC
