### ISSUE TITLE
Global Hot Key can't bring the window back to front if the app is in system tray

### ISSUE THREAD

**Issue by tildebox** [thomaslevesque/NHotkey#22] opened 2020-05-07 07:58 UTC
I tried your project with "Hardcodet NotifyIcon for WPF" - at the moment no .Net Core support. I tried with .NET Framework 4.7.2.

GitHub: https://github.com/hardcodet/wpf-notifyicon

Project Site: http://www.hardcodet.net/wpf-notifyicon

I tried the "Windowless Sample". If the app is in system tray the global hot key can't bring the window back to front.

```
this.WindowState = WindowState.Normal;
this.Activate();
// this.Topmost = true;
// this.Topmost = false;
this.Focus();
```

Any ideas how I can achieve this?

**Comment by thomaslevesque** [comment] 2020-05-07 08:21
Hi @tildebox,

Forcing a window to the foreground has always been a pain, because Windows does its best to prevent apps from stealing focus...

Is the problem specific to the global hotkey?

BTW, you also need to `Show()` the window. If it's in the systray, it's in a hidden state.

**Comment by thomaslevesque** [comment] 2020-05-07 08:37
In general, a window can only bring itself to the foreground in response to an user action. I'm not sure exactly what Windows considers a user action; I suspect it has something to do with the Window receiving a message.
NHotkey uses a "message-only window" to receive hotkey messages, so it's not *your* Window that receives the message. This might be why you're unable to bring the window to the front.

I'll need to experiment a bit to understand what the problem is. It might be unrelated to NHotkey, but if it's related, I'll see if I can do something about it.

**Comment by thomaslevesque** [comment] 2020-05-07 20:16
I just tried it, it works fine. I think you just forgot to make the window visible by calling `Show()`. Here's what I did:

```csharp
this.Show();
this.Activate();
this.Focus();
```

Anyway, it looks like the problem has nothing to do with NHotkey, so I'm closing the issue.

**Closed by thomaslevesque** 2020-05-07 20:16 UTC
